### ISSUE TITLE
flutter ios

### ISSUE THREAD

**Issue by niallmca** [vagran/dxf-viewer#1]
Hello,

Is there any way to use this dxf-viewer as part of an IOS app in flutter?
ie to display .DXF image on iPhone in flutter/dart app?

Thanks,
Niall

**Comment by vagran** [comment]
This is JavaScript library targeting a browser with WebGL and WebWorker support. I am not familiar with Flutter, but seems its native application for iOS is not backed by a browser. Flutter web-app may be the only viable option, however I cannot comment if such kind of JavaScript library can be easily integrated in such application.
