### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Snailya** [vagran/dxf-viewer#12]
need typescript declare

**Comment by vagran** [comment]
I have added some kind of [declarations](https://github.com/vagran/dxf-viewer/blob/master/src/index.d.ts). However I am not a big Typescript expert yet, and actually cannot test its correctness, so some review would be appreciated.

**Comment by vagran** [comment]
Assuming the added declarations are OK, so closing this issue. In case of some problems, feel free to open new issue.
