### ISSUE TITLE
Wrong render result of 'Dimension pre-rendered block'

### ISSUE THREAD

**Issue by Sululu666** [vagran/dxf-viewer#122]
The problem is when open this file, some dimension part not display.
[zhongwangpeixun1.zip](https://github.com/user-attachments/files/17869530/zhongwangpeixun1.zip)

Here is the result:
1.by other product:
![image](https://github.com/user-attachments/assets/75749c94-b8f0-40eb-acfe-fc96a233df5d)

2.by dxf-viewer:
![image](https://github.com/user-attachments/assets/03158b13-be95-46c0-8aab-0c7049c30b01)

It took a while found that when not use dimension pre-rendered block,
![image](https://github.com/user-attachments/assets/33307373-b658-44e9-bcf5-c1cb8a008508)

those part will show: 
![image](https://github.com/user-attachments/assets/b188a8ab-2552-49ea-9a85-162905073a2f)
(with wrong text as actualMeasurement of dimension not handle)

Question:
Is there any lack of judgement to decide whether use 'Dimension pre-rendered block', like the content integrity of block?
If it is because development is not complete, please ignore this issue.

**Comment by Sululu666** [comment]
Thanks for the answer.
By the way, I've found that those pre-renderd blocks' color and colorIndex are both undefined
and for temporary test I set the color to 'byLayer.
![企业微信截图_17323338052003](https://github.com/user-attachments/assets/a7ffe341-e565-4ab5-bab3-2119c85cb763)

then the render result is right:
![image](https://github.com/user-attachments/assets/38e6290c-c68a-42c3-828d-151cd3f86d25)

hope this give you train of thought

**Comment by vagran** [comment]
Seems to be fixed by #123. You can check it on [demo page](https://vagran.github.io/dxf-viewer-example/) which has the recent version deployed.
