### ISSUE TITLE
Wrong layer of inserted block

### ISSUE THREAD

**Issue by Sululu666** [vagran/dxf-viewer#123]
The block whose layer was modified during insertion is not correctly placed on the modified layer.
Many blocks are placed in layer 0. (when toggle the layer panel 0 layer, there are many entities should not belong to 0)

Here I've print some inserts with corresponding block:
![企业微信截图_17326802155582](https://github.com/user-attachments/assets/d1c628fa-3ff8-4b25-82d4-2ffc49209528)
![企业微信截图_17326796881977](https://github.com/user-attachments/assets/13c088bd-cc91-4878-b98b-d00550e2547b)

**Comment by vagran** [comment]
Do you have any sample file which illustrates the problem? Maybe some minimal synthetic example.

**Comment by vagran** [comment]
Seems you have attached `dwg` file instead of `dxf`.

**Comment by vagran** [comment]
Fixed in the most recent release 1.0.37. Thanks, @Sululu666, for your effort in the problem pre-analysis, which helped a lot for the prompt fix!
