### ISSUE TITLE
Text display

### ISSUE THREAD

**Issue by Wanik999** [vagran/dxf-viewer#17]
Hello, now I have a question, how to convert the font in dxf into Chinese.
![image](https://user-images.githubusercontent.com/62334553/211992399-57f11231-98e8-4824-bdc3-e94ce3886bed.png)

**Comment by vagran** [comment]
Hello,
This is one of incomplete features mentioned in the readme. Need to process some [special sequences and unicode escapes](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-Core/files/GUID-518E1A9D-398C-4A8A-AC32-2D85590CDBE1-htm.html) in strings. Actually, if a file is saved in UTF-8 encoding, these escapes are not needed and text can be specified directly and it can be now properly displayed. I will try to revise this feature in several days.

**Comment by vagran** [comment]
Fixed in v1.0.19. Note, that you still need proper fonts specified to render corresponding unicode glyphs.
