### ISSUE TITLE
How to run in my local machine 

### ISSUE THREAD

**Issue by sivayekula** [vagran/dxf-viewer#2]
Could you please explain how to run this in my local machine

**Comment by vagran** [comment]
The simplest way is to check this repository: https://github.com/vagran/dxf-viewer-example-src
Check it out, pull npm dependecies by `npm install` command and then run by `npm run serve` command. The example will be available by `https://localhost:9001/` URL.

**Comment by sivayekula** [comment]
Thank you so much. it's working fine
