### ISSUE TITLE
How to implement the POLYLINE type

### ISSUE THREAD

**Issue by kimkanghyune** [vagran/dxf-viewer#27]
[POLYINE type case](https://github.com/vagran/dxf-viewer/blob/2a114eb5d04fe90016f4db1ea850b91d00bfb73c/src/DxfScene.js#L169)

While looking at the source code, I noticed that there is no logic to handle the POLYLINE type.
I knew there was a part in [three-dxf](https://github.com/gdsestimating/three-dxf/blob/20e14cbd13735e16a1b691f7b864936dd688fb74/src/index.js#L200) that handles this type. Wouldn't it be easy to make by referring to the logic?

I still have a hard time with dxf-viewer's compression algorithm. I'd like to contribute to this open source, but it's not easy.

**Comment by vagran** [comment]
Actually there IS a logic for polyline case, it is handled in the same way as LWPOLYLINE entity (this is how this switch should be read), it should work. Do you have any sample file with the problematic case? I would take a look.

**Comment by vagran** [comment]
Assuming there is no actual issue.
