### ISSUE TITLE
Provide information about dimension

### ISSUE THREAD

**Issue by kimkanghyune** [vagran/dxf-viewer#28]
[DXF Reference](https://damassets.autodesk.net/content/dam/autodesk/www/developer-network/platform-technologies/autocad-dxf-archive/acad_r12_dxf.pdf)
[Common Dimension Group Codes](https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-EDD54EAC-A339-4EBA-AEA6-EC8066505E2B)

The dimension line separates the material as above.

And in [dxf-parser](https://github.com/gdsestimating/dxf-parser/blob/master/src/entities/dimension.ts) , it is classified in the code above.
I think you need to create a separate group for one dimension line.
so, I think you should create a separate rendering class and classification logic for one dimension line.

**Comment by vagran** [comment]
Hello,
I have seen your pull request, but it does not seem to be valid, I have tried to run your branch, but it still does not display any dimensions. BTW, I have added [contribution guidelines](https://github.com/vagran/dxf-viewer/blob/master/CONTRIBUTING.md) to make it clear what a valid pull request should look like.
Regarding dimensions support. This indeed is the most awaited entity to support next from the TODO list. I will probably proceed with looking into it as well (actually I have already started some activities during this weekend). For now I have the following findings and roadmap:

1. For the initial implementation we can limit support to linear dimensions (vertical, horizontal, rotated and aligned) with a very limited features support (will need to identify them for release notes and readme, and also update list of todo features for `DIMENSION` entity).
2. [Here](https://ezdxf.readthedocs.io/en/stable/tutorials/linear_dimension.html#tut-linear-dimension) is a good source of additional information about parameters defining the dimension.
3. There are quite a lot of system variables which define how the dimension should look like. Some initial minimal subset should be identified to start with (rendered dimension size and position -related).
4. These variable can be originated from several sources, taking precedence in the following order:
  a. [Dimension style override](https://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-6A4C31C0-4988-499C-B5A4-15582E433B0F) in `DIMENSION` entity.
  b. Dimension style defined in [`DIMSTYLE` table](https://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-F2FAD36F-0CE3-4943-9DAD-A9BCD2AE81DA) entry. Need to implement this table parsing and lookup.
  c. DXF file header.
  d. Some predefined default values ([example](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/AutoCAD-Core/files/GUID-A17A69D7-25EF-4F57-B4EB-D53A56AB909C-htm.html)).
5. Dimension entity should be decomposed into rendering primitives in the same way it is done for other entities. It should be lines, text, and solid trianges for arrowhead arrow style.
6. Initially we can render all dimensions with a default arrowhead, providing possibility to finish this feature later.
7. Dimension text is either overridden or calculated as distance between the dimension anchor points. When overriding text some [special values](https://ezdxf.readthedocs.io/en/stable/tutorials/linear_dimension.html#overriding-measurement-text) should be recognized - single space " " to suppress text, missing group tag or empty string is default text. "<>" pattern in the override text should be replaced by the default text. Default text units and formatting is defined by several system variables like `DIMLFAC`, `DIMLUNIT` and `DIMFRAC`

**Comment by vagran** [comment]
[v1.0.21](https://github.com/vagran/dxf-viewer/releases/tag/v1.0.21) released with most of this stuff implemented. Feel free to open new issues for still unimplemented dimension-related features (preferably with example files attached).
