### ISSUE TITLE
Support for pdf

### ISSUE THREAD

**Issue by sivayekula** [vagran/dxf-viewer#3]
Hi vagran, I have a pdf file with multiple dxf images. I have attached sample pdf with single image. Please help me how to extract this pdf or any suggestions. Thanks
[Sample Vector PDF _outlines.pdf](https://github.com/vagran/dxf-viewer/files/6657100/Sample.Vector.PDF_outlines.pdf)

**Comment by vagran** [comment]
Unfortunately this is definitely out of scope of this library. By the way, the embedded images have nothing to do with DXF, this is just vector graphics embedded into PDF. If you want just extract it, use, for example, Inkscape vector graphics editor, just open your file in it, edit and save in any format you want.

**Comment by sivayekula** [comment]
Ok, Thanks
