### ISSUE TITLE
Координаты/Coordinates

### ISSUE THREAD

**Issue by rusellxgm** [vagran/dxf-viewer#38]
Добрый день! Можно ли получить координаты клика на чертеже? / Is it possible to get the coordinates of the click in the drawing?

**Comment by vagran** [comment]
Добрый день! События (`CustomEvent`) эмитятся на элемент `canvas`, который можно получить методом `DxfViewer.GetCanvas()`. У имён событий добавляется префикс `__dxf_`. Для событий указателя добавляется поле `position` с координатами в пространстве модели. Оригинальное событие доступно в поле `domEvent`. Пока обрабатываются только `pointerdown` и `pointerup`. Скорей всего в будущем этот интерфейс будет переработан.
```
viewer.GetCanvas().addEventListener("__dxf_pointerdown", e => console.log(e.details.position))
```
