### ISSUE TITLE
how to deal transform of insert in insert?

### ISSUE THREAD

**Issue by ghost** [vagran/dxf-viewer#4]
I also want show dxf draws by three, I meet a problem, for example, 
![image](https://user-images.githubusercontent.com/33376447/131066214-b58ba869-427e-4568-a4c6-650959f6e895.png)
my code
![image](https://user-images.githubusercontent.com/33376447/131066290-c3317f02-1b13-4d0e-91b2-171230af733d.png)
the structure 
![image](https://user-images.githubusercontent.com/33376447/131066470-0d414603-52c8-4655-8625-2fd85de090b4.png)
your
![image](https://user-images.githubusercontent.com/33376447/131067208-11709b2b-071b-4fdc-a14a-f9033abc4247.png)
I don't know how to deal it. Orz

**Comment by lunhuidaozhu** [comment]
Thank you.

**Comment by lunhuidaozhu** [comment]
I remember, in addition to dxF-Viewer, we can also learn related specifications in the official DXF documentation.
It looks like this:
https://knowledge.autodesk.com/zh-hans/support/autocad/learn-explore/caas/downloads/downloads/CHS/content/download-install-autocad-2021-product-help.html

**Comment by vagran** [comment]
Yes, I used it during dxf- viewer implementation. But it is just file format specification (which has also many tricky areas not fully clear from the specification itself, e.g. trick with the extrusion direction, its influence to 2D render). It will not tell anything about proper implementation of renderer of such files.
