### ISSUE TITLE
Shading is only applied to the first few uploaded DXF file.

### ISSUE THREAD

**Issue by ali-faiz-brainx** [vagran/dxf-viewer#44]
I'm building an app that allows users to upload DXF files and render them in the browser using Three.js. To shade the inner part of the DXF geometry, I'm using a MeshBasicMaterial with a grey color.

The problem is that the shading is only applied to the first few uploaded DXF file, and not the subsequent files. I have tried different approaches to fix this issue, including setting the render order of the shaded meshes, but the issue persists.

  `  createShapeObj(vertices, isColored) {
         const objVertices = this._TransformVertex(vertices.map(el=>new three.Vector2(el.x, el.y)));

        let material = new three.MeshBasicMaterial( { color: isColored ? 0xE5E5E5 : 0xffffff } ); //shading only inner geometry
        const shape = new three.Shape();
        shape.moveTo(objVertices[0].x, objVertices[0].y);
        for(let i=1;i<objVertices.length;i++){
            shape.lineTo(objVertices[i].x, objVertices[i].y)
        }
        const geometry = new three.ShapeGeometry(shape);
        const mesh = new three.Mesh( geometry, material ) ;

        return {mesh};
    }`

Note: I have tried dxf files

**Comment by vagran** [comment]
Hello,
I did not really get the idea. Where do you place this code example? Which kind of DXF entity are you trying to shade? There is currently support of solid infill (with a color specified in DXF) for  `3DFACE`, `SOLID` and `POLYLINE` with polyface mesh type. They are rendered as solid polygons when `dxfScene.wireframeMesh` is set to true. Does not it suit your needs?

**Comment by ali-faiz-brainx** [comment]
Hi @vagran did you get a chance to look into this?

**Comment by ali-faiz-brainx** [comment]
Hi @vagran I have just noticed that I get dataUrl from getCanvas function and then use it as png and the rendering of files is working fine but their URL shows weird behavior of not filling the image. Do you know about this behavior?

**Comment by vagran** [comment]
Sounds like some out-of-sync canvas access. I do not really know if something like this is possible for canvas and WebGLRenderer. Are you sure, the viewer does not re-render its view after you have drawn your overlay? Quick suggestion could be setting breakpoint in the browser on `DxfViewer.Render()` function (or adding debug trace into console), and checking if it is not called after you have drawn your overlay. Another quick idea - do you reuse DxfViewer instance for each drawing? If yes, may be it is worth to try to create a fresh new instance for each one.
