### ISSUE TITLE
The dimension does not have a valid layer assigned to it.

### ISSUE THREAD

**Issue by kimkanghyune** [vagran/dxf-viewer#54]
![dxf viewer](https://i.ibb.co/RgR2dWf/dim1.png)
dxf viewer

![autocad viewer](https://i.ibb.co/1nWfw7J/dim2.png)
autocad viewer

It's not just the color that's different, there's a problem with it not being assigned to the correct layer.

**Comment by vagran** [comment]
Nice finding, thank! Just fixed this in master. Will update npm package soon as well since this is quite critical bug.
