### ISSUE TITLE
Some paper space is rendered.

### ISSUE THREAD

**Issue by kimkanghyune** [vagran/dxf-viewer#56]
![paperspace](https://i.ibb.co/TYqn5TK/paperspace.png)
![find](https://i.ibb.co/DVgj4Z8/paperspace2.png)

I found it rendered in a very small picture like the one pictured above.

**Comment by vagran** [comment]
I have added option `sceneOptions.suppressPaperSpace`. Paper space entities will not be rendered when set to `true`. Default is `false` since some use cases still want to see paper space.
