### ISSUE TITLE
can export a click event?

### ISSUE THREAD

**Issue by ChinaBruce** [vagran/dxf-viewer#57]
hi 
   Can there be a click event in dxf-viewer? I want to obtain information about clicked icons through click events.

thanks.

**Comment by vagran** [comment]
Hi! Events (CustomEvent) are emitted for `canvas` element, which you can get by `DxfViewer.GetCanvas()` method. Event names are prefixed by `__dxf_`. For pointer event `position` property is added with model space coordinates. Original event is available in `domEvent` property. For now only `pointerdown` and `pointerup` are re-emitted in such a way. Most probably this interface will be changed in the future.
```
viewer.GetCanvas().addEventListener("__dxf_pointerdown", e => console.log(e.details.position))
```
