### ISSUE TITLE
AxesHelper

### ISSUE THREAD

**Issue by epiccheesepie** [vagran/dxf-viewer#65]
Артем привет! У меня некоторые проблемы с тем, чтобы переместить оси x,y в начало чертежа. Т.е. я хочу, чтобы чертеж был в такой области, чтобы он не занимал отрицательные координаты (находился правее и выше от осей; с началом в самой левой и нижней точке чертежа) Надеюсь понятно объяснил...
Можешь помочь с этим, если это возможно? Вот несколько скриншотов с демонстрацией того, что некоторые элементы чертежа находятся под осью y, и левее x
Я пытался манипулировать значением из origin, но слабо выходит
<img width="1401" alt="Снимок экрана 2023-05-25 в 15 09 11" src="https://github.com/vagran/dxf-viewer/assets/61943387/cd644d7f-8962-4fac-bf16-16ceaa784300">
<img width="1401" alt="Снимок экрана 2023-05-25 в 15 09 30" src="https://github.com/vagran/dxf-viewer/assets/61943387/38a48b6d-7c84-4b81-ac4d-ebda0267c955">

**Comment by vagran** [comment]
Привет! Чертёж занимает те координаты, в которых он определён, они неизменны. Если тебе просто нужно нарисовать оси, но не обязательно прохдящие через начало координат, ну тогда и рисуй не из нуля, а из нижней левой точки. Границы элементов чертежа можно получить из свойства `DxfViewer.bounds`. Соответственно, рисуй из `[viewer.bounds.minX - marginX, viewer.bounds.minY - marginY]`, определив какой-то отступ `margin`, (например как 5% от размера чертежа по соответствующей оси).
