### ISSUE TITLE
Return type of GetCamera()

### ISSUE THREAD

**Issue by shintarokkk** [vagran/dxf-viewer#69]
Hi
Thanks for creating and maintaining this great project!

I found a small bug in `index.d.ts`. I think return type of DxfViewer.GetCamera() should be "OrthographicCamera" instead of "Camera".
https://github.com/vagran/dxf-viewer/blob/e07b8d93d93708dbffa161ea46e214430957874a/src/index.d.ts#L56

**Comment by vagran** [comment]
Hi, thanks for the report. I have fixed as proposed. However, it might change in the future, since 3D view is planned to implement, so perspective camera may be used as well.
