### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by jayantpaliwal** [vagran/dxf-viewer#86]
dxf-viewer/src/DxfViewer.js 834:60
Module parse failed: Unexpected token (834:60)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 

      **const material = materialFactory.call(this.viewer, this.viewer._TransformColor(color),
                                              instanceBatch?.GetInstanceType() ?? InstanceType.NONE)**

{
 "three": "^0.155.0"
}

**Comment by vagran** [comment]
If you are targeting an old JS version, see [example repository](https://github.com/vagran/dxf-viewer-example-src) for Babel example. Make sure null coalescing operator and optional chaining is enabled in [Babel config](https://github.com/vagran/dxf-viewer-example-src/blob/master/babel.config.js). Also ensure the library is transpiled in [Vue config](https://github.com/vagran/dxf-viewer-example-src/blob/master/vue.config.js).
