### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Aupire** [vagran/dxf-viewer#87]
I want to use dxf-viewer but I get this error when I use browserify.

browserify ./src/app.js -o ./public/bundle.js : 
```
/node_modules/dxf-viewer/src/index.js:1
export {DxfFetcher} from "./DxfFetcher"
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by ezelbanaan** [comment]
I get the same issue when using this in combination with Next.JS. It would be fixed by adding `"type":"module"` to the [package.json](https://github.com/vagran/dxf-viewer/blob/master/package.json) as requested in #90

**Comment by vagran** [comment]
Merged. Sorry for late response, had to allocate time to verify it works with the example project.
