### ISSUE TITLE
DXF Viewer not supporting some entities

### ISSUE THREAD

**Issue by CunhaaS** [vagran/dxf-viewer#9]
Hi vagran, 

First of all this is an amazing viewer, but when I was testing you deployed demo, I noticed that some entities are not being handled.
I'll leave here two prints for you to see.
This is what the dxf supposed to look like.

![dxf](https://user-images.githubusercontent.com/36960445/156547677-16bab606-21ea-40db-ade2-dc9b48731452.png)

And here's what is happening.

![dxf-2](https://user-images.githubusercontent.com/36960445/156548243-ffa51352-99a7-49ca-89fe-b5db8ab9100b.png)

I don't if was your choice to not to handle this type of entity, but as I said earlier this is an amazing work.

Best regards,
José Cunha

**Comment by vagran** [comment]
Hello,
Seems you mostly need dimensions and hatching. Hatching is quite challenging to implement so it is probably not in the nearest future roadmap. The dimensions seems to be the most demanded entity from the list of still unimplemented ones. And it does not look like it requires any complex changes, so probably this is the next entity to implement in the roadmap. I cannot guarantee any timeframe now but I will do my best to implement it in a couple of weeks (weekends are currently the only time I can spend for this project). You can help if you have any file with various dimensions examples which you can share with me.

**Comment by 15389244925** [comment]
First of all this is an amazing viewer, but when I was testing you deployed demo, I noticed that some entities are not being handled.
I'll leave here two prints for you to see.
This is what the dxf supposed to look like.
![image](https://user-images.githubusercontent.com/104416417/181442939-d4e33912-448c-4f88-836c-2a59ff2896cf.png)
And here's what is happening.
![image](https://user-images.githubusercontent.com/104416417/181443094-a3b494cc-f0f8-40eb-9854-09be167bc22b.png)

**Comment by vagran** [comment]
Basic support for dimension is now available in [v1.0.21](https://github.com/vagran/dxf-viewer/releases/tag/v1.0.21).
