### ISSUE TITLE
Possible to display DXF from string var, not by fetching URL ?

### ISSUE THREAD

**Issue by loicroybon** [vagran/dxf-viewer#97]
Hello,
I build DXF file content with this lib : @tarikjabiri/dxf
So I get string variables containing DXF content.
I would like to use vagran/dxf-viewer to display the generated DXF based on this content. 

I use Vue3

Possible ?

**Comment by vagran** [comment]
I do not see any reason why it can be impossible. See [current reference example](https://github.com/vagran/dxf-viewer-example-src/blob/master/src/App.vue), use `Blob` with string content to create object URL.

**Comment by loicroybon** [comment]
I'm sorry but could you provide a short simple please ? I think I already tried your idea without success

**Comment by vagran** [comment]
```
const s = loadDxfAsString()
const b = new Blob([s], {type: "image/x-dxf"})
const url = URL.createObjectURL(b)
```
