### ISSUE TITLE
How to adopt this for BabylonJS

### ISSUE THREAD

**Issue by MartinPyka** [vagran/dxf-viewer#98]
I am wondering, how I would interface BabylonJS with this dxf-viewer. I was looking through you code and thought that maybe the file DxfScene.js is one where I would need to replace the ThreeJS-way of creating 3d objects by the BabylonJS-way. What do you think? Where should I start, when I would try to replace ThreeJS with BabylonJS for the view. 

Best,
Martin

**Comment by vagran** [comment]
Unfortunately, I am not familiar with BabylonJS. However, I doubt you need to modify DxfScene.js for that. It produces DXF scene which is platform-independent representation of DXF entities, optimized for high-performant batch rendering. In contrast, DxfViewer.js contains code which converts this pure geometry data to three.js-specific scene. That is what you need to rewrite.

**Comment by MartinPyka** [comment]
Alright, thanks for the hint. I will dig deeper into that
